name: Blog

on:
  push:
    branches:
      - master
  issues:
    types: [opened, closed, edited, milestoned, labeled, unlabeled, reopened, demilestoned]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v3
        with:
          repository: Yidadaa/Issue-Blog-With-Github-Action
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          wget https://raw.githubusercontent.com/Yidadaa/Yidadaa.github.io/master/.github/workflows/cv.md -O ./src/cv.md
          wget https://raw.githubusercontent.com/Yidadaa/Yidadaa.github.io/master/.github/workflows/custom.js -O ./src/.vuepress/custom.js
          npm install vuepress
          npm install
          npm run action
          npm run build
          npm run deploy
